#!/usr/bin/env bash
# Regenerates flart_filters test fixtures from real `dart`/`flutter` command
# output.
#
# Idempotent: re-run any time. Each fixture file gets a header comment with
# the source command and the Dart/Flutter version it was captured from.
# Test code skips comment lines starting with `#` at the top.
set -euo pipefail

cd "$(dirname "$0")/.."
ROOT="$(pwd)"
LAB="${TMPDIR:-/tmp}/flart_fixture_lab"
FIXTURES_DIR="$ROOT/packages/flart_filters/test/fixtures"

mkdir -p "$FIXTURES_DIR"
rm -rf "$LAB"
mkdir -p "$LAB/lib"

DART_VERSION_LINE="$(dart --version 2>&1 | head -1)"

# Lab pubspec — pure Dart, fast resolve.
cat > "$LAB/pubspec.yaml" <<'YAML'
name: flart_fixture_lab
description: Throwaway lab for generating filter fixtures.
publish_to: none
version: 0.0.1
environment:
  sdk: ^3.5.0
dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0
YAML

# Enable the recommended lint set so we see INFO|LINT rows in fixtures —
# without this dart analyze only produces ERROR/WARNING rows.
cat > "$LAB/analysis_options.yaml" <<'YAML'
include: package:lints/recommended.yaml
YAML

# Resolve the lab path to its canonical form too — macOS reports
# /private/var/... for /var/... symlinks, which would otherwise leak into
# fixtures and make them machine-specific.
LAB_REAL="$(cd "$LAB" && pwd -P)"

# Replace path placeholders with stable tokens so fixtures are reproducible
# across machines / users / tmp roots.
sanitize_paths() {
  sed -e "s|$LAB_REAL|<LAB>|g" -e "s|$LAB|<LAB>|g" -e "s|$HOME|<HOME>|g"
}

write_fixture() {
  local name="$1"
  local cmd="$2"
  local body_file="$3"
  {
    printf '# Generated by tools/generate_fixtures.sh\n'
    printf '# %s\n' "$DART_VERSION_LINE"
    printf '# Source command: %s\n' "$cmd"
    printf '# DO NOT EDIT MANUALLY — re-run script if needed.\n'
    printf '#\n'
    cat "$body_file" | sanitize_paths
  } > "$FIXTURES_DIR/$name"
  echo "  → $FIXTURES_DIR/$name"
}

cd "$LAB"
dart pub get >/dev/null 2>&1 || true

# Analyze: clean -------------------------------------------------------------
cat > lib/clean.dart <<'DART'
void main() => print('clean');
DART

# Analyze: warnings only — two WARNING severity rows (unused_local_variable)
cat > lib/warnings.dart <<'DART'
void main() {
  final unused1 = 'a';
  final unused2 = 'b';
  print('with warnings');
}
DART

# Analyze: errors only -------------------------------------------------------
cat > lib/errors.dart <<'DART'
void main() {
  String s = 42;
  s.missingMethod();
}
DART

# Analyze: mixed errors + warnings -------------------------------------------
cat > lib/mixed.dart <<'DART'
import 'dart:io';
void main() {
  String s = 42;
  final unused = 'x';
  print(Platform.operatingSystem);
  print(s);
}
DART

# Analyze: generated file (should be bucketed separately) --------------------
cat > lib/generated.g.dart <<'DART'
void main() {
  final unused = 'gen';
  print('generated');
}
DART

ANALYZE='dart analyze --format=machine'

# Format scenarios -----------------------------------------------------------
# `dart format` modifies files in-place by default and prints `Formatted <p>`
# for changed files + a summary. With `--output=none` it dry-runs and uses
# `Changed`/`Unchanged` prefixes. We capture both so the filter handles both
# styles.
echo "Regenerating format fixtures…"
cat > lib/already_formatted.dart <<'DART'
void main() {
  print('hello');
}
DART
cat > lib/needs_format.dart <<'DART'
void main(){print('hello');for(var i=0;i<3;i++){print(i);}}
DART

# Default mode (modifies file, prints "Formatted <path>" for changed).
# Reset file content first since previous runs may have formatted it.
cat > lib/needs_format.dart <<'DART'
void main(){print('hello');for(var i=0;i<3;i++){print(i);}}
DART
TMP=$(mktemp)
dart format lib/already_formatted.dart lib/needs_format.dart > "$TMP" 2>&1 || true
write_fixture "format_default_some_changed.txt" \
  "dart format lib/already_formatted.dart lib/needs_format.dart" \
  "$TMP"
rm -f "$TMP"

# Dry-run mode (--output=none, prints "Changed"/"Unchanged" + summary).
# Reset content to make output deterministic.
cat > lib/needs_format.dart <<'DART'
void main(){print('hello');for(var i=0;i<3;i++){print(i);}}
DART
TMP=$(mktemp)
dart format --output=none lib/already_formatted.dart lib/needs_format.dart > "$TMP" 2>&1 || true
write_fixture "format_dryrun_some_changed.txt" \
  "dart format --output=none lib/already_formatted.dart lib/needs_format.dart" \
  "$TMP"
rm -f "$TMP"

# All unchanged.
TMP=$(mktemp)
dart format lib/already_formatted.dart > "$TMP" 2>&1 || true
write_fixture "format_all_unchanged.txt" \
  "dart format lib/already_formatted.dart" \
  "$TMP"
rm -f "$TMP"

# Clean scenarios ------------------------------------------------------------
# `dart` has no `clean` subcommand — flart clean wraps `flutter clean`.
# Skip in the lab (no Flutter SDK assumed). The clean filter is trivial
# enough that we cover it with a tiny synthetic stdout sample in unit tests.

# Test scenarios -------------------------------------------------------------
# `dart test --reporter=json` emits one JSON event per line. We capture two
# realistic scenarios: all-pass and some-fail.
echo "Regenerating test fixtures…"
mkdir -p test
cat > test/passing_test.dart <<'DART'
import 'package:test/test.dart';

void main() {
  group('arithmetic', () {
    test('addition', () => expect(1 + 1, 2));
    test('subtraction', () => expect(5 - 3, 2));
  });
  test('string concat', () => expect('a' + 'b', 'ab'));
}
DART
cat > test/failing_test.dart <<'DART'
import 'package:test/test.dart';

void main() {
  test('pass-a', () => expect(1, 1));
  test('fail-string', () {
    expect('actual-value', equals('expected-value'));
  });
  test('pass-b', () => expect(2, 2));
  test('fail-throws', () {
    throw StateError('boom from the test');
  });
}
DART
dart pub get >/dev/null 2>&1 || true

TMP=$(mktemp)
dart test --reporter=json test/passing_test.dart > "$TMP" 2>&1 || true
write_fixture "test_all_pass.json" \
  "dart test --reporter=json test/passing_test.dart" \
  "$TMP"
rm -f "$TMP"

TMP=$(mktemp)
dart test --reporter=json test/failing_test.dart > "$TMP" 2>&1 || true
write_fixture "test_some_fail.json" \
  "dart test --reporter=json test/failing_test.dart" \
  "$TMP"
rm -f "$TMP"

# Pub scenarios -------------------------------------------------------------
# These use a *separate* lab directory so we control the dependency state.
echo "Regenerating pub fixtures…"
PUB_LAB="$LAB/_pub_lab"
mkdir -p "$PUB_LAB"
cat > "$PUB_LAB/pubspec.yaml" <<'YAML'
name: pub_fixture_lab
publish_to: none
version: 0.0.1
environment:
  sdk: ^3.5.0
dependencies:
  yaml: ^3.1.0
  path: ^1.8.0
YAML

# pub_get_fresh: initial resolve with several deps installed.
TMP=$(mktemp)
(cd "$PUB_LAB" && dart pub get) > "$TMP" 2>&1 || true
write_fixture "pub_get_with_changes.txt" \
  "dart pub get  # initial resolve, several deps added" \
  "$TMP"
rm -f "$TMP"

# pub_get_clean: re-run with nothing to change.
TMP=$(mktemp)
(cd "$PUB_LAB" && dart pub get) > "$TMP" 2>&1 || true
write_fixture "pub_get_clean.txt" \
  "dart pub get  # re-run, no changes" \
  "$TMP"
rm -f "$TMP"

# pub_upgrade_clean: no upgrades available (everything already at max).
TMP=$(mktemp)
(cd "$PUB_LAB" && dart pub upgrade) > "$TMP" 2>&1 || true
write_fixture "pub_upgrade_clean.txt" \
  "dart pub upgrade  # nothing to upgrade" \
  "$TMP"
rm -f "$TMP"

# pub_get_conflict: deliberately incompatible constraint.
mkdir -p "$LAB/_pub_conflict_lab"
cat > "$LAB/_pub_conflict_lab/pubspec.yaml" <<'YAML'
name: pub_conflict_lab
publish_to: none
version: 0.0.1
environment:
  sdk: ^3.5.0
dependencies:
  yaml: '>=3.1.0 <3.1.1'
  path: ^1.8.0
  source_span: ^99.99.99
YAML
TMP=$(mktemp)
(cd "$LAB/_pub_conflict_lab" && dart pub get) > "$TMP" 2>&1 || true
write_fixture "pub_get_conflict.txt" \
  "dart pub get  # version solving failure (synthetic constraints)" \
  "$TMP"
rm -f "$TMP"

echo "Regenerating analyze fixtures…"
for scenario in clean warnings errors mixed; do
  TMP=$(mktemp)
  $ANALYZE "lib/$scenario.dart" > "$TMP" 2>&1 || true
  write_fixture "analyze_$scenario.txt" \
    "dart analyze --format=machine lib/$scenario.dart" \
    "$TMP"
  rm -f "$TMP"
done

# Mixed scenario including the generated file — captures both real and
# generated paths in one fixture.
TMP=$(mktemp)
$ANALYZE lib/ > "$TMP" 2>&1 || true
write_fixture "analyze_with_generated.txt" \
  "dart analyze --format=machine lib/" \
  "$TMP"
rm -f "$TMP"

cd "$ROOT"
rm -rf "$LAB"
echo "Done."
